AWSTemplateFormatVersion: "2010-09-09"

Description:  EC2 Auto Scaling Group

Parameters:
  Prefix:
    Type: String

Resources:
  EC2AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "${Prefix}-asg"
      VPCZoneIdentifier:
        - !ImportValue SubnetPrivate1AId
        - !ImportValue SubnetPrivate1CId
      LaunchTemplate:
        LaunchTemplateId: !ImportValue LaunchTemplateId
        Version: !ImportValue LaunchTemplateVersion
      MaxSize: "1"
      MinSize: "1"
      DesiredCapacity: "1"
      HealthCheckType: ELB
      TargetGroupARNs:
        - !ImportValue TargetGroupId
